# Generated by Django 6.0.1 on 2026-06-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='service',
            name='staff',
            field=models.ManyToManyField(blank=True, to='salon.staff'),
        ),
    ]
