# Generated by Django 6.0.1 on 2026-06-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_service_commission_percent_service_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
