# Generated by Django 6.0.4 on 2026-10-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_appointment_approval_status_appointment_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicktasksale',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('M-Pesa', 'M-Pesa'), ('Bank', 'Bank')], default='Cash', max_length=20),
        ),
    ]
