# Generated by Django 6.0.4 on 2026-10-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0011_quicktasksale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='expense_receipts/'),
        ),
    ]
