# Generated by Django 6.0.1 on 2026-02-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_staffattendance_staffleave_staffpenalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
